sudo: false

language: bash

jobs:
  include:
    - stage: test
      script:
        - echo "1"
      deploy:
        - provider: s3
          access_key_id: 111
          secret_access_key: 222
          bucket: kbc-ui-assets
          local-dir: dist
          upload-dir: kbc-ui
          acl: public_read
          skip_cleanup: true
          cache_control: max-age=31536000
          on:
            tags: true
            branch: master
      if: branch = master OR tag IS present
